# Generated by Django 4.1.3 on 2022-11-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='minimum_amount',
            field=models.IntegerField(default=500),
        ),
    ]
