# Generated by Django 4.1.3 on 2022-11-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_email_varified',
            new_name='is_email_verified',
        ),
    ]
